# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!

target 'DemoRestaurante' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Presentacion
  pod 'IQKeyboardManagerSwift', '~> 5.0'
  
  # Infraestructura
  

end
